@startuml
class InWallRemovalStrategy {
    + InWallRemovalStrategy(inWallObjectsPlacementData:PlacementGridData, placementData:PlacementGridData, gridManager:GridManager)
}
InWallPlacementStrategy <|-- InWallRemovalStrategy
@enduml
