@startuml
class InWallPlacementStrategy {
    + InWallPlacementStrategy(wallPlacementData:PlacementGridData, placementData:PlacementGridData, gridManager:GridManager)
    + <<override>> StartSelection(mousePosition:Vector3, selectionData:SelectionData) : void
    + <<override>> ModifySelection(mousePosition:Vector3, selectionData:SelectionData) : bool
    + <<override>> FinishSelection(selectionData:SelectionData) : void
}
SelectionStrategy <|-- InWallPlacementStrategy
@enduml
